### ISSUE TITLE
BKCommonLib gets disabled during server startup.

### ISSUE THREAD

**Issue by Agrrox** [bergerhealer/BKCommonLib#114]
##### Mohist  version:  1.12.2 build #169

<hr>

#### Problem or bug:
[23:59:09] [Server thread/INFO] [Mohist]: Enabling BKCommonLib v1.16.4-v2
[23:59:09] [Server thread/ERROR] [Mohist]: [BKCommonLib] This version of BKCommonLib is not compatible with: Paperspigot (git-Mohist-1.12.2-169 (MC: 1.12.2)) : v1_12_R1 (Minecraft v1_12_R1)
[23:59:09] [Server thread/ERROR] [Mohist]: [BKCommonLib] It could be that BKCommonLib has to be updated, as the current version is built for MC 1.8 to 1.15.2, 1.16.1, 1.16.2, 1.16.3 and 1.16.4
[23:59:09] [Server thread/ERROR] [Mohist]: [BKCommonLib] Please look for a new updated BKCommonLib version that is compatible:
[23:59:09] [Server thread/ERROR] [Mohist]: [BKCommonLib] https://www.spigotmc.org/resources/bkcommonlib.39590/
[23:59:09] [Server thread/ERROR] [Mohist]: [BKCommonLib] Unstable development builds for MC v1_12_R1 may be found on our continuous integration server:
[23:59:09] [Server thread/ERROR] [Mohist]: [BKCommonLib] https://ci.mg-dev.eu/job/BKCommonLib/
[23:59:09] [Server thread/ERROR] [Mohist]: [BKCommonLib] BKCommonLib and all depending plugins will now disable...
[23:59:09] [Server thread/INFO] [Mohist]: Disabling BKCommonLib v1.16.4-v2

#### Server Plugins/Mods:
Mods:
Aroma1997Core-1.12.2-2.0.0.2.b167
AromaBackup-1.12.2-3.0.0.0.b135
ccpregen-0.0.17
CubicChunks-1.12.2-0.0.1180.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.140.0-SNAPSHOT-all
morecompressions-3.0.0.0.b135
rhino-1.7.12-0
terra121-0.1.5
terramap-1.0.0-beta6.6
worldedit-forge-mc1.12.2-6.1.11-cubicchunks-SNAPSHOT-dist

Plugins:
AdvancedBan-2.1.9-RELEASE
BetterBrushes
BKCommonLib-1.16.4-v2
bungeeguard-backend v1.0
EssentialsX-2.18.2.0
EssentialsXSpawn-2.18.2.0
HeadsInventory-1.9.2
HeadsPluginAPI-1.9.0
HolographicDisplays
LuckPerms-Bukkit-5.2.35
PlaceholderAPI-2.10.3
ProtocolLib v4.5.1
sledgehammer-0.4.2-bukkit
TouchscreenHolograms v1.4.2
Vault 1.5.6-b49
VentureChat v2.20.1
VoxelSniper-5.171.0-CC_COMPAT-SNAPSHOT
worldedit-bukkit-6.1.9
worldguard-bukkit-6.2.2
WorldGuardExtraFlags v4.1.4

#### Steps to reproduce:
Install plugin on Mohist 1.12.2 and launch the server.

#### Logs
[latest.log](https://github.com/bergerhealer/BKCommonLib/files/5798851/latest.log)

**Comment by bergerkiller** [comment]
I think this was fixed, but not yet released https://github.com/bergerhealer/BKCommonLib/commit/d555d0f8c0229bc098046a2262710a35a768309d

https://ci.mg-dev.eu/job/BKCommonLib/

**Comment by Agrrox** [comment]
> I think this was fixed, but not yet released [d555d0f](https://github.com/bergerhealer/BKCommonLib/commit/d555d0f8c0229bc098046a2262710a35a768309d)
> 
> https://ci.mg-dev.eu/job/BKCommonLib/

I've installed that snapshot and it works, however when using Light Cleaner I run into some issues.
I get these errors during startup
![Screen_Shot_2021-01-13_at_09 15 06](https://user-images.githubusercontent.com/10901821/104648753-e2d9ee80-56b3-11eb-9bb7-2cd695fb459f.png)
And I get high cpu and ram usage when Light Cleaner is in the plugins.
![Screen_Shot_2021-01-13_at_09 16 00](https://user-images.githubusercontent.com/10901821/104648777-f1280a80-56b3-11eb-9e59-1399988df355.png)
![Screen_Shot_2021-01-13_at_09 11 43](https://user-images.githubusercontent.com/10901821/104648780-f1c0a100-56b3-11eb-8016-430b6ca00d94.png)

**Comment by bergerkiller** [comment]
The errors you see are actual errors in the server itself that show up as chunks are loaded by the plugin. Are you doing a worldwide cleaning operation? Because loading and re-saving the chunks requires a lot of cpu and ram.

**Comment by Agrrox** [comment]
> The errors you see are actual errors in the server itself that show up as chunks are loaded by the plugin. Are you doing a worldwide cleaning operation? Because loading and re-saving the chunks requires a lot of cpu and ram.
> 
> If youre using the automatic cleaning during chunk gen, I recommend turning that off for now, as due to a server conflict its causing runaway chunk loading/generation


Issue still occurs when Light Cleaner config is set as follows:
```
#> This is the configuration of Light Cleaner, in here you can enable or disable features as you please

# The minimum amount of memory (in MB) allowed while processing chunk lighting
# If the remaining free memory drops below this value, measures are taken to reduce it
# Memory will be Garbage Collected and all worlds will be saved to free memory
# The process will be stalled for so long free memory is below this value
minFreeMemory: 400

# Whether to skip processing chunks at the edge of the world
# Setting this to true prevents additional chunks being generated there
# This does mean the border chunks do not get cleaned
skipWorldEdge: true

# Sets whether lighting is cleaned up for newly generated chunks
# This will eliminate dark shadows during world generation
autoCleanEnabled: false

# Sets whether lighting is cleaned up when players perform WorldEdit operations
# This is primarily useful for FastAsyncWorldEdit
autoCleanWorldEditEnabled: false

# How many chunks are asynchronously loaded at the same time
# Setting this value too high may overflow the internal queues. Too low and it will idle too much.
asyncLoadConcurrency: 50

# A list of world names that have saving disabled
# Light Cleaner will not save these worlds to free up memory,
# and will not write persistent PendingLight.dat entries for these worlds
unsavedWorldNames: []
```

**Comment by bergerkiller** [comment]
Use this one: https://ci.mg-dev.eu/job/Light-Cleaner/107/

What do /timings say? (/timings on, wait a few minutes, /timings paste)

**Comment by Agrrox** [comment]
timings report:
https://timings.aikar.co/?id=8c944a3242a141b485392d67ba24b474

also I encountered this error during startup:
[error.log](https://github.com/bergerhealer/BKCommonLib/files/5819854/error.log)

**Comment by bergerkiller** [comment]
Oh this is Mohist **with** cubic chunks mod installed? That changes the question quite a lot. Looks like a lot of things are broken, will need to look into that.

Do first use this build of bkcommonlib: https://ci.mg-dev.eu/job/BKCommonLib/989/

Because recent versions of mohist broke compatibility

**Comment by Agrrox** [comment]
Seems like using these two exact versions of plugins, fixed the issue.
https://ci.mg-dev.eu/job/BKCommonLib/989/
https://ci.mg-dev.eu/job/Light-Cleaner/107/

- no memory or cpu performance issues (apart of couple of spikes but thats probably not related)
- light cleaner is working
- no error messages in console during start up.

**Comment by bergerkiller** [comment]
Good to hear, if you feel the issues are fully solved (maybe check timings) you can close the issue

**Comment by Agrrox** [comment]
Issue solved. Thanks!
